# Dockerfile.airflow-secure
FROM python:3.11-slim

# System dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Airflow and dependencies
RUN pip install --no-cache-dir \
    apache-airflow==2.10.0 \
    psycopg2-binary

# Set working directory
WORKDIR /opt/airflow

# Create logs folder with permissions
RUN mkdir -p /opt/airflow/logs && chmod -R 777 /opt/airflow/logs
