FROM apache/airflow:2.10.0

ARG LOCAL_UID=1000
RUN useradd --shell /bin/bash --uid ${LOCAL_UID} --non-unique --comment "Local User" --create-home localuser

USER ${LOCAL_UID}
WORKDIR /opt/airflow

# No instalar paquetes extra
# No abrir puertos innecesarios
